version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "8000:1194/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
     - ./openvpn-data/logs:/var/log/
